coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "**/*_test.go"
  - "**/mocks"
  - "**/mocks/**"
  - "**/mock_*.go"
  - "tests"
  - "tests/**"
