// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// NewPasswordResetTokenRepository creates a new instance of PasswordResetTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordResetTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordResetTokenRepository {
	mock := &PasswordResetTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasswordResetTokenRepository is an autogenerated mock type for the PasswordResetTokenRepository type
type PasswordResetTokenRepository struct {
	mock.Mock
}

type PasswordResetTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordResetTokenRepository) EXPECT() *PasswordResetTokenRepository_Expecter {
	return &PasswordResetTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type PasswordResetTokenRepository
func (_mock *PasswordResetTokenRepository) Create(ctx context.Context, token *models.PasswordResetToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.PasswordResetToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasswordResetTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PasswordResetTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *models.PasswordResetToken
func (_e *PasswordResetTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *PasswordResetTokenRepository_Create_Call {
	return &PasswordResetTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *PasswordResetTokenRepository_Create_Call) Run(run func(ctx context.Context, token *models.PasswordResetToken)) *PasswordResetTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.PasswordResetToken
		if args[1] != nil {
			arg1 = args[1].(*models.PasswordResetToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordResetTokenRepository_Create_Call) Return(err error) *PasswordResetTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasswordResetTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *models.PasswordResetToken) error) *PasswordResetTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type PasswordResetTokenRepository
func (_mock *PasswordResetTokenRepository) Delete(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasswordResetTokenRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PasswordResetTokenRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *PasswordResetTokenRepository_Expecter) Delete(ctx interface{}, email interface{}) *PasswordResetTokenRepository_Delete_Call {
	return &PasswordResetTokenRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, email)}
}

func (_c *PasswordResetTokenRepository_Delete_Call) Run(run func(ctx context.Context, email string)) *PasswordResetTokenRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordResetTokenRepository_Delete_Call) Return(err error) *PasswordResetTokenRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasswordResetTokenRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, email string) error) *PasswordResetTokenRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type PasswordResetTokenRepository
func (_mock *PasswordResetTokenRepository) FindByEmail(ctx context.Context, email string) (*models.PasswordResetToken, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *models.PasswordResetToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.PasswordResetToken, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.PasswordResetToken); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasswordResetTokenRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type PasswordResetTokenRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *PasswordResetTokenRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *PasswordResetTokenRepository_FindByEmail_Call {
	return &PasswordResetTokenRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *PasswordResetTokenRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *PasswordResetTokenRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordResetTokenRepository_FindByEmail_Call) Return(passwordResetToken *models.PasswordResetToken, err error) *PasswordResetTokenRepository_FindByEmail_Call {
	_c.Call.Return(passwordResetToken, err)
	return _c
}

func (_c *PasswordResetTokenRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.PasswordResetToken, error)) *PasswordResetTokenRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}
