// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// NewPasskeyRepository creates a new instance of PasskeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasskeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasskeyRepository {
	mock := &PasskeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasskeyRepository is an autogenerated mock type for the PasskeyRepository type
type PasskeyRepository struct {
	mock.Mock
}

type PasskeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PasskeyRepository) EXPECT() *PasskeyRepository_Expecter {
	return &PasskeyRepository_Expecter{mock: &_m.Mock}
}

// CountByUserID provides a mock function for the type PasskeyRepository
func (_mock *PasskeyRepository) CountByUserID(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasskeyRepository_CountByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserID'
type PasskeyRepository_CountByUserID_Call struct {
	*mock.Call
}

// CountByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PasskeyRepository_Expecter) CountByUserID(ctx interface{}, userID interface{}) *PasskeyRepository_CountByUserID_Call {
	return &PasskeyRepository_CountByUserID_Call{Call: _e.mock.On("CountByUserID", ctx, userID)}
}

func (_c *PasskeyRepository_CountByUserID_Call) Run(run func(ctx context.Context, userID string)) *PasskeyRepository_CountByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyRepository_CountByUserID_Call) Return(n int64, err error) *PasskeyRepository_CountByUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *PasskeyRepository_CountByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *PasskeyRepository_CountByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type PasskeyRepository
func (_mock *PasskeyRepository) Create(ctx context.Context, passkey *models.Passkey) error {
	ret := _mock.Called(ctx, passkey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Passkey) error); ok {
		r0 = returnFunc(ctx, passkey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasskeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PasskeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - passkey *models.Passkey
func (_e *PasskeyRepository_Expecter) Create(ctx interface{}, passkey interface{}) *PasskeyRepository_Create_Call {
	return &PasskeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, passkey)}
}

func (_c *PasskeyRepository_Create_Call) Run(run func(ctx context.Context, passkey *models.Passkey)) *PasskeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Passkey
		if args[1] != nil {
			arg1 = args[1].(*models.Passkey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyRepository_Create_Call) Return(err error) *PasskeyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasskeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, passkey *models.Passkey) error) *PasskeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type PasskeyRepository
func (_mock *PasskeyRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasskeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PasskeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PasskeyRepository_Expecter) Delete(ctx interface{}, id interface{}) *PasskeyRepository_Delete_Call {
	return &PasskeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PasskeyRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *PasskeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyRepository_Delete_Call) Return(err error) *PasskeyRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasskeyRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *PasskeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function for the type PasskeyRepository
func (_mock *PasskeyRepository) DeleteByUserID(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasskeyRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type PasskeyRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *PasskeyRepository_Expecter) DeleteByUserID(ctx interface{}, id interface{}, userID interface{}) *PasskeyRepository_DeleteByUserID_Call {
	return &PasskeyRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, id, userID)}
}

func (_c *PasskeyRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, id string, userID string)) *PasskeyRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PasskeyRepository_DeleteByUserID_Call) Return(err error) *PasskeyRepository_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasskeyRepository_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *PasskeyRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCredentialID provides a mock function for the type PasskeyRepository
func (_mock *PasskeyRepository) FindByCredentialID(ctx context.Context, credentialID string) (*models.Passkey, error) {
	ret := _mock.Called(ctx, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCredentialID")
	}

	var r0 *models.Passkey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Passkey, error)); ok {
		return returnFunc(ctx, credentialID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Passkey); ok {
		r0 = returnFunc(ctx, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Passkey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, credentialID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasskeyRepository_FindByCredentialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCredentialID'
type PasskeyRepository_FindByCredentialID_Call struct {
	*mock.Call
}

// FindByCredentialID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID string
func (_e *PasskeyRepository_Expecter) FindByCredentialID(ctx interface{}, credentialID interface{}) *PasskeyRepository_FindByCredentialID_Call {
	return &PasskeyRepository_FindByCredentialID_Call{Call: _e.mock.On("FindByCredentialID", ctx, credentialID)}
}

func (_c *PasskeyRepository_FindByCredentialID_Call) Run(run func(ctx context.Context, credentialID string)) *PasskeyRepository_FindByCredentialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyRepository_FindByCredentialID_Call) Return(passkey *models.Passkey, err error) *PasskeyRepository_FindByCredentialID_Call {
	_c.Call.Return(passkey, err)
	return _c
}

func (_c *PasskeyRepository_FindByCredentialID_Call) RunAndReturn(run func(ctx context.Context, credentialID string) (*models.Passkey, error)) *PasskeyRepository_FindByCredentialID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type PasskeyRepository
func (_mock *PasskeyRepository) FindByID(ctx context.Context, id string) (*models.Passkey, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Passkey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Passkey, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Passkey); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Passkey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasskeyRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PasskeyRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PasskeyRepository_Expecter) FindByID(ctx interface{}, id interface{}) *PasskeyRepository_FindByID_Call {
	return &PasskeyRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *PasskeyRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *PasskeyRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyRepository_FindByID_Call) Return(passkey *models.Passkey, err error) *PasskeyRepository_FindByID_Call {
	_c.Call.Return(passkey, err)
	return _c
}

func (_c *PasskeyRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Passkey, error)) *PasskeyRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type PasskeyRepository
func (_mock *PasskeyRepository) FindByUserID(ctx context.Context, userID string) ([]models.Passkey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []models.Passkey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.Passkey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Passkey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Passkey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasskeyRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type PasskeyRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PasskeyRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *PasskeyRepository_FindByUserID_Call {
	return &PasskeyRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *PasskeyRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *PasskeyRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyRepository_FindByUserID_Call) Return(passkeys []models.Passkey, err error) *PasskeyRepository_FindByUserID_Call {
	_c.Call.Return(passkeys, err)
	return _c
}

func (_c *PasskeyRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]models.Passkey, error)) *PasskeyRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type PasskeyRepository
func (_mock *PasskeyRepository) Update(ctx context.Context, passkey *models.Passkey) error {
	ret := _mock.Called(ctx, passkey)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Passkey) error); ok {
		r0 = returnFunc(ctx, passkey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasskeyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PasskeyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - passkey *models.Passkey
func (_e *PasskeyRepository_Expecter) Update(ctx interface{}, passkey interface{}) *PasskeyRepository_Update_Call {
	return &PasskeyRepository_Update_Call{Call: _e.mock.On("Update", ctx, passkey)}
}

func (_c *PasskeyRepository_Update_Call) Run(run func(ctx context.Context, passkey *models.Passkey)) *PasskeyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Passkey
		if args[1] != nil {
			arg1 = args[1].(*models.Passkey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyRepository_Update_Call) Return(err error) *PasskeyRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasskeyRepository_Update_Call) RunAndReturn(run func(ctx context.Context, passkey *models.Passkey) error) *PasskeyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
