// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// NewPersonalAccessTokenRepository creates a new instance of PersonalAccessTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonalAccessTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonalAccessTokenRepository {
	mock := &PersonalAccessTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PersonalAccessTokenRepository is an autogenerated mock type for the PersonalAccessTokenRepository type
type PersonalAccessTokenRepository struct {
	mock.Mock
}

type PersonalAccessTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PersonalAccessTokenRepository) EXPECT() *PersonalAccessTokenRepository_Expecter {
	return &PersonalAccessTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type PersonalAccessTokenRepository
func (_mock *PersonalAccessTokenRepository) Create(ctx context.Context, token *models.PersonalAccessToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.PersonalAccessToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PersonalAccessTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PersonalAccessTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *models.PersonalAccessToken
func (_e *PersonalAccessTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *PersonalAccessTokenRepository_Create_Call {
	return &PersonalAccessTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *PersonalAccessTokenRepository_Create_Call) Run(run func(ctx context.Context, token *models.PersonalAccessToken)) *PersonalAccessTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.PersonalAccessToken
		if args[1] != nil {
			arg1 = args[1].(*models.PersonalAccessToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PersonalAccessTokenRepository_Create_Call) Return(err error) *PersonalAccessTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PersonalAccessTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *models.PersonalAccessToken) error) *PersonalAccessTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type PersonalAccessTokenRepository
func (_mock *PersonalAccessTokenRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PersonalAccessTokenRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PersonalAccessTokenRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PersonalAccessTokenRepository_Expecter) Delete(ctx interface{}, id interface{}) *PersonalAccessTokenRepository_Delete_Call {
	return &PersonalAccessTokenRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PersonalAccessTokenRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *PersonalAccessTokenRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PersonalAccessTokenRepository_Delete_Call) Return(err error) *PersonalAccessTokenRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PersonalAccessTokenRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *PersonalAccessTokenRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUser provides a mock function for the type PersonalAccessTokenRepository
func (_mock *PersonalAccessTokenRepository) DeleteByUser(ctx context.Context, id string, userID string) (int64, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PersonalAccessTokenRepository_DeleteByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUser'
type PersonalAccessTokenRepository_DeleteByUser_Call struct {
	*mock.Call
}

// DeleteByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *PersonalAccessTokenRepository_Expecter) DeleteByUser(ctx interface{}, id interface{}, userID interface{}) *PersonalAccessTokenRepository_DeleteByUser_Call {
	return &PersonalAccessTokenRepository_DeleteByUser_Call{Call: _e.mock.On("DeleteByUser", ctx, id, userID)}
}

func (_c *PersonalAccessTokenRepository_DeleteByUser_Call) Run(run func(ctx context.Context, id string, userID string)) *PersonalAccessTokenRepository_DeleteByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PersonalAccessTokenRepository_DeleteByUser_Call) Return(n int64, err error) *PersonalAccessTokenRepository_DeleteByUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *PersonalAccessTokenRepository_DeleteByUser_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) (int64, error)) *PersonalAccessTokenRepository_DeleteByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function for the type PersonalAccessTokenRepository
func (_mock *PersonalAccessTokenRepository) FindByToken(ctx context.Context, token string) (*models.PersonalAccessToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *models.PersonalAccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.PersonalAccessToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.PersonalAccessToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PersonalAccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PersonalAccessTokenRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type PersonalAccessTokenRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *PersonalAccessTokenRepository_Expecter) FindByToken(ctx interface{}, token interface{}) *PersonalAccessTokenRepository_FindByToken_Call {
	return &PersonalAccessTokenRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *PersonalAccessTokenRepository_FindByToken_Call) Run(run func(ctx context.Context, token string)) *PersonalAccessTokenRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PersonalAccessTokenRepository_FindByToken_Call) Return(personalAccessToken *models.PersonalAccessToken, err error) *PersonalAccessTokenRepository_FindByToken_Call {
	_c.Call.Return(personalAccessToken, err)
	return _c
}

func (_c *PersonalAccessTokenRepository_FindByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*models.PersonalAccessToken, error)) *PersonalAccessTokenRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type PersonalAccessTokenRepository
func (_mock *PersonalAccessTokenRepository) GetByUser(ctx context.Context, userID string) ([]models.PersonalAccessToken, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []models.PersonalAccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.PersonalAccessToken, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.PersonalAccessToken); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PersonalAccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PersonalAccessTokenRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type PersonalAccessTokenRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *PersonalAccessTokenRepository_Expecter) GetByUser(ctx interface{}, userID interface{}) *PersonalAccessTokenRepository_GetByUser_Call {
	return &PersonalAccessTokenRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID)}
}

func (_c *PersonalAccessTokenRepository_GetByUser_Call) Run(run func(ctx context.Context, userID string)) *PersonalAccessTokenRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PersonalAccessTokenRepository_GetByUser_Call) Return(personalAccessTokens []models.PersonalAccessToken, err error) *PersonalAccessTokenRepository_GetByUser_Call {
	_c.Call.Return(personalAccessTokens, err)
	return _c
}

func (_c *PersonalAccessTokenRepository_GetByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]models.PersonalAccessToken, error)) *PersonalAccessTokenRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastUsed provides a mock function for the type PersonalAccessTokenRepository
func (_mock *PersonalAccessTokenRepository) UpdateLastUsed(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PersonalAccessTokenRepository_UpdateLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastUsed'
type PersonalAccessTokenRepository_UpdateLastUsed_Call struct {
	*mock.Call
}

// UpdateLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PersonalAccessTokenRepository_Expecter) UpdateLastUsed(ctx interface{}, id interface{}) *PersonalAccessTokenRepository_UpdateLastUsed_Call {
	return &PersonalAccessTokenRepository_UpdateLastUsed_Call{Call: _e.mock.On("UpdateLastUsed", ctx, id)}
}

func (_c *PersonalAccessTokenRepository_UpdateLastUsed_Call) Run(run func(ctx context.Context, id string)) *PersonalAccessTokenRepository_UpdateLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PersonalAccessTokenRepository_UpdateLastUsed_Call) Return(err error) *PersonalAccessTokenRepository_UpdateLastUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PersonalAccessTokenRepository_UpdateLastUsed_Call) RunAndReturn(run func(ctx context.Context, id string) error) *PersonalAccessTokenRepository_UpdateLastUsed_Call {
	_c.Call.Return(run)
	return _c
}
