// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/contracts"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewRepositoryRegistry creates a new instance of RepositoryRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryRegistry {
	mock := &RepositoryRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryRegistry is an autogenerated mock type for the RepositoryRegistry type
type RepositoryRegistry struct {
	mock.Mock
}

type RepositoryRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryRegistry) EXPECT() *RepositoryRegistry_Expecter {
	return &RepositoryRegistry_Expecter{mock: &_m.Mock}
}

// DB provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// RepositoryRegistry_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type RepositoryRegistry_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) DB() *RepositoryRegistry_DB_Call {
	return &RepositoryRegistry_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *RepositoryRegistry_DB_Call) Run(run func()) *RepositoryRegistry_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_DB_Call) Return(dB *gorm.DB) *RepositoryRegistry_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *RepositoryRegistry_DB_Call) RunAndReturn(run func() *gorm.DB) *RepositoryRegistry_DB_Call {
	_c.Call.Return(run)
	return _c
}

// IsTeamSubscribed provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) IsTeamSubscribed(ctx context.Context, teamID string) bool {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for IsTeamSubscribed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// RepositoryRegistry_IsTeamSubscribed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTeamSubscribed'
type RepositoryRegistry_IsTeamSubscribed_Call struct {
	*mock.Call
}

// IsTeamSubscribed is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *RepositoryRegistry_Expecter) IsTeamSubscribed(ctx interface{}, teamID interface{}) *RepositoryRegistry_IsTeamSubscribed_Call {
	return &RepositoryRegistry_IsTeamSubscribed_Call{Call: _e.mock.On("IsTeamSubscribed", ctx, teamID)}
}

func (_c *RepositoryRegistry_IsTeamSubscribed_Call) Run(run func(ctx context.Context, teamID string)) *RepositoryRegistry_IsTeamSubscribed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryRegistry_IsTeamSubscribed_Call) Return(b bool) *RepositoryRegistry_IsTeamSubscribed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *RepositoryRegistry_IsTeamSubscribed_Call) RunAndReturn(run func(ctx context.Context, teamID string) bool) *RepositoryRegistry_IsTeamSubscribed_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserAdmin provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) IsUserAdmin(ctx context.Context, userID string) bool {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserAdmin")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// RepositoryRegistry_IsUserAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserAdmin'
type RepositoryRegistry_IsUserAdmin_Call struct {
	*mock.Call
}

// IsUserAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *RepositoryRegistry_Expecter) IsUserAdmin(ctx interface{}, userID interface{}) *RepositoryRegistry_IsUserAdmin_Call {
	return &RepositoryRegistry_IsUserAdmin_Call{Call: _e.mock.On("IsUserAdmin", ctx, userID)}
}

func (_c *RepositoryRegistry_IsUserAdmin_Call) Run(run func(ctx context.Context, userID string)) *RepositoryRegistry_IsUserAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryRegistry_IsUserAdmin_Call) Return(b bool) *RepositoryRegistry_IsUserAdmin_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *RepositoryRegistry_IsUserAdmin_Call) RunAndReturn(run func(ctx context.Context, userID string) bool) *RepositoryRegistry_IsUserAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// Passkey provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) Passkey() contracts.PasskeyRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Passkey")
	}

	var r0 contracts.PasskeyRepository
	if returnFunc, ok := ret.Get(0).(func() contracts.PasskeyRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.PasskeyRepository)
		}
	}
	return r0
}

// RepositoryRegistry_Passkey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Passkey'
type RepositoryRegistry_Passkey_Call struct {
	*mock.Call
}

// Passkey is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) Passkey() *RepositoryRegistry_Passkey_Call {
	return &RepositoryRegistry_Passkey_Call{Call: _e.mock.On("Passkey")}
}

func (_c *RepositoryRegistry_Passkey_Call) Run(run func()) *RepositoryRegistry_Passkey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_Passkey_Call) Return(passkeyRepository contracts.PasskeyRepository) *RepositoryRegistry_Passkey_Call {
	_c.Call.Return(passkeyRepository)
	return _c
}

func (_c *RepositoryRegistry_Passkey_Call) RunAndReturn(run func() contracts.PasskeyRepository) *RepositoryRegistry_Passkey_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordResetToken provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) PasswordResetToken() contracts.PasswordResetTokenRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PasswordResetToken")
	}

	var r0 contracts.PasswordResetTokenRepository
	if returnFunc, ok := ret.Get(0).(func() contracts.PasswordResetTokenRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.PasswordResetTokenRepository)
		}
	}
	return r0
}

// RepositoryRegistry_PasswordResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordResetToken'
type RepositoryRegistry_PasswordResetToken_Call struct {
	*mock.Call
}

// PasswordResetToken is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) PasswordResetToken() *RepositoryRegistry_PasswordResetToken_Call {
	return &RepositoryRegistry_PasswordResetToken_Call{Call: _e.mock.On("PasswordResetToken")}
}

func (_c *RepositoryRegistry_PasswordResetToken_Call) Run(run func()) *RepositoryRegistry_PasswordResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_PasswordResetToken_Call) Return(passwordResetTokenRepository contracts.PasswordResetTokenRepository) *RepositoryRegistry_PasswordResetToken_Call {
	_c.Call.Return(passwordResetTokenRepository)
	return _c
}

func (_c *RepositoryRegistry_PasswordResetToken_Call) RunAndReturn(run func() contracts.PasswordResetTokenRepository) *RepositoryRegistry_PasswordResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// PersonalAccessToken provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) PersonalAccessToken() contracts.PersonalAccessTokenRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PersonalAccessToken")
	}

	var r0 contracts.PersonalAccessTokenRepository
	if returnFunc, ok := ret.Get(0).(func() contracts.PersonalAccessTokenRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.PersonalAccessTokenRepository)
		}
	}
	return r0
}

// RepositoryRegistry_PersonalAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersonalAccessToken'
type RepositoryRegistry_PersonalAccessToken_Call struct {
	*mock.Call
}

// PersonalAccessToken is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) PersonalAccessToken() *RepositoryRegistry_PersonalAccessToken_Call {
	return &RepositoryRegistry_PersonalAccessToken_Call{Call: _e.mock.On("PersonalAccessToken")}
}

func (_c *RepositoryRegistry_PersonalAccessToken_Call) Run(run func()) *RepositoryRegistry_PersonalAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_PersonalAccessToken_Call) Return(personalAccessTokenRepository contracts.PersonalAccessTokenRepository) *RepositoryRegistry_PersonalAccessToken_Call {
	_c.Call.Return(personalAccessTokenRepository)
	return _c
}

func (_c *RepositoryRegistry_PersonalAccessToken_Call) RunAndReturn(run func() contracts.PersonalAccessTokenRepository) *RepositoryRegistry_PersonalAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// Session provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) Session() contracts.SessionRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Session")
	}

	var r0 contracts.SessionRepository
	if returnFunc, ok := ret.Get(0).(func() contracts.SessionRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.SessionRepository)
		}
	}
	return r0
}

// RepositoryRegistry_Session_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Session'
type RepositoryRegistry_Session_Call struct {
	*mock.Call
}

// Session is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) Session() *RepositoryRegistry_Session_Call {
	return &RepositoryRegistry_Session_Call{Call: _e.mock.On("Session")}
}

func (_c *RepositoryRegistry_Session_Call) Run(run func()) *RepositoryRegistry_Session_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_Session_Call) Return(sessionRepository contracts.SessionRepository) *RepositoryRegistry_Session_Call {
	_c.Call.Return(sessionRepository)
	return _c
}

func (_c *RepositoryRegistry_Session_Call) RunAndReturn(run func() contracts.SessionRepository) *RepositoryRegistry_Session_Call {
	_c.Call.Return(run)
	return _c
}

// Team provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) Team() contracts.TeamRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Team")
	}

	var r0 contracts.TeamRepository
	if returnFunc, ok := ret.Get(0).(func() contracts.TeamRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.TeamRepository)
		}
	}
	return r0
}

// RepositoryRegistry_Team_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Team'
type RepositoryRegistry_Team_Call struct {
	*mock.Call
}

// Team is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) Team() *RepositoryRegistry_Team_Call {
	return &RepositoryRegistry_Team_Call{Call: _e.mock.On("Team")}
}

func (_c *RepositoryRegistry_Team_Call) Run(run func()) *RepositoryRegistry_Team_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_Team_Call) Return(teamRepository contracts.TeamRepository) *RepositoryRegistry_Team_Call {
	_c.Call.Return(teamRepository)
	return _c
}

func (_c *RepositoryRegistry_Team_Call) RunAndReturn(run func() contracts.TeamRepository) *RepositoryRegistry_Team_Call {
	_c.Call.Return(run)
	return _c
}

// TeamInvitation provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) TeamInvitation() contracts.TeamInvitationRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TeamInvitation")
	}

	var r0 contracts.TeamInvitationRepository
	if returnFunc, ok := ret.Get(0).(func() contracts.TeamInvitationRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.TeamInvitationRepository)
		}
	}
	return r0
}

// RepositoryRegistry_TeamInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamInvitation'
type RepositoryRegistry_TeamInvitation_Call struct {
	*mock.Call
}

// TeamInvitation is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) TeamInvitation() *RepositoryRegistry_TeamInvitation_Call {
	return &RepositoryRegistry_TeamInvitation_Call{Call: _e.mock.On("TeamInvitation")}
}

func (_c *RepositoryRegistry_TeamInvitation_Call) Run(run func()) *RepositoryRegistry_TeamInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_TeamInvitation_Call) Return(teamInvitationRepository contracts.TeamInvitationRepository) *RepositoryRegistry_TeamInvitation_Call {
	_c.Call.Return(teamInvitationRepository)
	return _c
}

func (_c *RepositoryRegistry_TeamInvitation_Call) RunAndReturn(run func() contracts.TeamInvitationRepository) *RepositoryRegistry_TeamInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// TeamMember provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) TeamMember() contracts.TeamMemberRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TeamMember")
	}

	var r0 contracts.TeamMemberRepository
	if returnFunc, ok := ret.Get(0).(func() contracts.TeamMemberRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.TeamMemberRepository)
		}
	}
	return r0
}

// RepositoryRegistry_TeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamMember'
type RepositoryRegistry_TeamMember_Call struct {
	*mock.Call
}

// TeamMember is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) TeamMember() *RepositoryRegistry_TeamMember_Call {
	return &RepositoryRegistry_TeamMember_Call{Call: _e.mock.On("TeamMember")}
}

func (_c *RepositoryRegistry_TeamMember_Call) Run(run func()) *RepositoryRegistry_TeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_TeamMember_Call) Return(teamMemberRepository contracts.TeamMemberRepository) *RepositoryRegistry_TeamMember_Call {
	_c.Call.Return(teamMemberRepository)
	return _c
}

func (_c *RepositoryRegistry_TeamMember_Call) RunAndReturn(run func() contracts.TeamMemberRepository) *RepositoryRegistry_TeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type RepositoryRegistry
func (_mock *RepositoryRegistry) User() contracts.UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 contracts.UserRepository
	if returnFunc, ok := ret.Get(0).(func() contracts.UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.UserRepository)
		}
	}
	return r0
}

// RepositoryRegistry_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type RepositoryRegistry_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
func (_e *RepositoryRegistry_Expecter) User() *RepositoryRegistry_User_Call {
	return &RepositoryRegistry_User_Call{Call: _e.mock.On("User")}
}

func (_c *RepositoryRegistry_User_Call) Run(run func()) *RepositoryRegistry_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryRegistry_User_Call) Return(userRepository contracts.UserRepository) *RepositoryRegistry_User_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *RepositoryRegistry_User_Call) RunAndReturn(run func() contracts.UserRepository) *RepositoryRegistry_User_Call {
	_c.Call.Return(run)
	return _c
}
