// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Create(ctx context.Context, session *models.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *models.Session
func (_e *SessionRepository_Expecter) Create(ctx interface{}, session interface{}) *SessionRepository_Create_Call {
	return &SessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *SessionRepository_Create_Call) Run(run func(ctx context.Context, session *models.Session)) *SessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Session
		if args[1] != nil {
			arg1 = args[1].(*models.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Create_Call) Return(err error) *SessionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, session *models.Session) error) *SessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionRepository_Expecter) Delete(ctx interface{}, id interface{}) *SessionRepository_Delete_Call {
	return &SessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SessionRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *SessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Delete_Call) Return(err error) *SessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *SessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByUser provides a mock function for the type SessionRepository
func (_mock *SessionRepository) DeleteAllByUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_DeleteAllByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByUser'
type SessionRepository_DeleteAllByUser_Call struct {
	*mock.Call
}

// DeleteAllByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionRepository_Expecter) DeleteAllByUser(ctx interface{}, userID interface{}) *SessionRepository_DeleteAllByUser_Call {
	return &SessionRepository_DeleteAllByUser_Call{Call: _e.mock.On("DeleteAllByUser", ctx, userID)}
}

func (_c *SessionRepository_DeleteAllByUser_Call) Run(run func(ctx context.Context, userID string)) *SessionRepository_DeleteAllByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_DeleteAllByUser_Call) Return(err error) *SessionRepository_DeleteAllByUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_DeleteAllByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *SessionRepository_DeleteAllByUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByUserExcept provides a mock function for the type SessionRepository
func (_mock *SessionRepository) DeleteAllByUserExcept(ctx context.Context, userID string, exceptID string) (int64, error) {
	ret := _mock.Called(ctx, userID, exceptID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByUserExcept")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, userID, exceptID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, userID, exceptID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, exceptID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_DeleteAllByUserExcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByUserExcept'
type SessionRepository_DeleteAllByUserExcept_Call struct {
	*mock.Call
}

// DeleteAllByUserExcept is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - exceptID string
func (_e *SessionRepository_Expecter) DeleteAllByUserExcept(ctx interface{}, userID interface{}, exceptID interface{}) *SessionRepository_DeleteAllByUserExcept_Call {
	return &SessionRepository_DeleteAllByUserExcept_Call{Call: _e.mock.On("DeleteAllByUserExcept", ctx, userID, exceptID)}
}

func (_c *SessionRepository_DeleteAllByUserExcept_Call) Run(run func(ctx context.Context, userID string, exceptID string)) *SessionRepository_DeleteAllByUserExcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionRepository_DeleteAllByUserExcept_Call) Return(n int64, err error) *SessionRepository_DeleteAllByUserExcept_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *SessionRepository_DeleteAllByUserExcept_Call) RunAndReturn(run func(ctx context.Context, userID string, exceptID string) (int64, error)) *SessionRepository_DeleteAllByUserExcept_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUser provides a mock function for the type SessionRepository
func (_mock *SessionRepository) DeleteByUser(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_DeleteByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUser'
type SessionRepository_DeleteByUser_Call struct {
	*mock.Call
}

// DeleteByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *SessionRepository_Expecter) DeleteByUser(ctx interface{}, id interface{}, userID interface{}) *SessionRepository_DeleteByUser_Call {
	return &SessionRepository_DeleteByUser_Call{Call: _e.mock.On("DeleteByUser", ctx, id, userID)}
}

func (_c *SessionRepository_DeleteByUser_Call) Run(run func(ctx context.Context, id string, userID string)) *SessionRepository_DeleteByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionRepository_DeleteByUser_Call) Return(err error) *SessionRepository_DeleteByUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_DeleteByUser_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *SessionRepository_DeleteByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Exists(ctx context.Context, id string) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type SessionRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionRepository_Expecter) Exists(ctx interface{}, id interface{}) *SessionRepository_Exists_Call {
	return &SessionRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *SessionRepository_Exists_Call) Run(run func(ctx context.Context, id string)) *SessionRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Exists_Call) Return(b bool, err error) *SessionRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *SessionRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, error)) *SessionRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type SessionRepository
func (_mock *SessionRepository) FindByID(ctx context.Context, id string) (*models.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type SessionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *SessionRepository_FindByID_Call {
	return &SessionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *SessionRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *SessionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_FindByID_Call) Return(session *models.Session, err error) *SessionRepository_FindByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Session, error)) *SessionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type SessionRepository
func (_mock *SessionRepository) GetByUser(ctx context.Context, userID string) ([]models.Session, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.Session, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Session); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type SessionRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionRepository_Expecter) GetByUser(ctx interface{}, userID interface{}) *SessionRepository_GetByUser_Call {
	return &SessionRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID)}
}

func (_c *SessionRepository_GetByUser_Call) Run(run func(ctx context.Context, userID string)) *SessionRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_GetByUser_Call) Return(sessions []models.Session, err error) *SessionRepository_GetByUser_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *SessionRepository_GetByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]models.Session, error)) *SessionRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastActivity provides a mock function for the type SessionRepository
func (_mock *SessionRepository) UpdateLastActivity(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastActivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_UpdateLastActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastActivity'
type SessionRepository_UpdateLastActivity_Call struct {
	*mock.Call
}

// UpdateLastActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionRepository_Expecter) UpdateLastActivity(ctx interface{}, id interface{}) *SessionRepository_UpdateLastActivity_Call {
	return &SessionRepository_UpdateLastActivity_Call{Call: _e.mock.On("UpdateLastActivity", ctx, id)}
}

func (_c *SessionRepository_UpdateLastActivity_Call) Run(run func(ctx context.Context, id string)) *SessionRepository_UpdateLastActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_UpdateLastActivity_Call) Return(err error) *SessionRepository_UpdateLastActivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_UpdateLastActivity_Call) RunAndReturn(run func(ctx context.Context, id string) error) *SessionRepository_UpdateLastActivity_Call {
	_c.Call.Return(run)
	return _c
}
