// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// NewTeamInvitationRepository creates a new instance of TeamInvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamInvitationRepository {
	mock := &TeamInvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TeamInvitationRepository is an autogenerated mock type for the TeamInvitationRepository type
type TeamInvitationRepository struct {
	mock.Mock
}

type TeamInvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamInvitationRepository) EXPECT() *TeamInvitationRepository_Expecter {
	return &TeamInvitationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TeamInvitationRepository
func (_mock *TeamInvitationRepository) Create(ctx context.Context, invitation *models.TeamInvitation) error {
	ret := _mock.Called(ctx, invitation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.TeamInvitation) error); ok {
		r0 = returnFunc(ctx, invitation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamInvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TeamInvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - invitation *models.TeamInvitation
func (_e *TeamInvitationRepository_Expecter) Create(ctx interface{}, invitation interface{}) *TeamInvitationRepository_Create_Call {
	return &TeamInvitationRepository_Create_Call{Call: _e.mock.On("Create", ctx, invitation)}
}

func (_c *TeamInvitationRepository_Create_Call) Run(run func(ctx context.Context, invitation *models.TeamInvitation)) *TeamInvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.TeamInvitation
		if args[1] != nil {
			arg1 = args[1].(*models.TeamInvitation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamInvitationRepository_Create_Call) Return(err error) *TeamInvitationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamInvitationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, invitation *models.TeamInvitation) error) *TeamInvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TeamInvitationRepository
func (_mock *TeamInvitationRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamInvitationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TeamInvitationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TeamInvitationRepository_Expecter) Delete(ctx interface{}, id interface{}) *TeamInvitationRepository_Delete_Call {
	return &TeamInvitationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TeamInvitationRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *TeamInvitationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamInvitationRepository_Delete_Call) Return(err error) *TeamInvitationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamInvitationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *TeamInvitationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type TeamInvitationRepository
func (_mock *TeamInvitationRepository) FindByEmail(ctx context.Context, teamID string, email string) (*models.TeamInvitation, error) {
	ret := _mock.Called(ctx, teamID, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *models.TeamInvitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.TeamInvitation, error)); ok {
		return returnFunc(ctx, teamID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.TeamInvitation); ok {
		r0 = returnFunc(ctx, teamID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, teamID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamInvitationRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type TeamInvitationRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - email string
func (_e *TeamInvitationRepository_Expecter) FindByEmail(ctx interface{}, teamID interface{}, email interface{}) *TeamInvitationRepository_FindByEmail_Call {
	return &TeamInvitationRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, teamID, email)}
}

func (_c *TeamInvitationRepository_FindByEmail_Call) Run(run func(ctx context.Context, teamID string, email string)) *TeamInvitationRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TeamInvitationRepository_FindByEmail_Call) Return(teamInvitation *models.TeamInvitation, err error) *TeamInvitationRepository_FindByEmail_Call {
	_c.Call.Return(teamInvitation, err)
	return _c
}

func (_c *TeamInvitationRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, teamID string, email string) (*models.TeamInvitation, error)) *TeamInvitationRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type TeamInvitationRepository
func (_mock *TeamInvitationRepository) FindByID(ctx context.Context, id string) (*models.TeamInvitation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.TeamInvitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.TeamInvitation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.TeamInvitation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamInvitationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type TeamInvitationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TeamInvitationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *TeamInvitationRepository_FindByID_Call {
	return &TeamInvitationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *TeamInvitationRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *TeamInvitationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamInvitationRepository_FindByID_Call) Return(teamInvitation *models.TeamInvitation, err error) *TeamInvitationRepository_FindByID_Call {
	_c.Call.Return(teamInvitation, err)
	return _c
}

func (_c *TeamInvitationRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.TeamInvitation, error)) *TeamInvitationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTeam provides a mock function for the type TeamInvitationRepository
func (_mock *TeamInvitationRepository) GetByTeam(ctx context.Context, teamID string) ([]models.TeamInvitation, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeam")
	}

	var r0 []models.TeamInvitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.TeamInvitation, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.TeamInvitation); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamInvitationRepository_GetByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeam'
type TeamInvitationRepository_GetByTeam_Call struct {
	*mock.Call
}

// GetByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *TeamInvitationRepository_Expecter) GetByTeam(ctx interface{}, teamID interface{}) *TeamInvitationRepository_GetByTeam_Call {
	return &TeamInvitationRepository_GetByTeam_Call{Call: _e.mock.On("GetByTeam", ctx, teamID)}
}

func (_c *TeamInvitationRepository_GetByTeam_Call) Run(run func(ctx context.Context, teamID string)) *TeamInvitationRepository_GetByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamInvitationRepository_GetByTeam_Call) Return(teamInvitations []models.TeamInvitation, err error) *TeamInvitationRepository_GetByTeam_Call {
	_c.Call.Return(teamInvitations, err)
	return _c
}

func (_c *TeamInvitationRepository_GetByTeam_Call) RunAndReturn(run func(ctx context.Context, teamID string) ([]models.TeamInvitation, error)) *TeamInvitationRepository_GetByTeam_Call {
	_c.Call.Return(run)
	return _c
}
