// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

type TeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamRepository) EXPECT() *TeamRepository_Expecter {
	return &TeamRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TeamRepository
func (_mock *TeamRepository) Create(ctx context.Context, team *models.Team) error {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Team) error); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - team *models.Team
func (_e *TeamRepository_Expecter) Create(ctx interface{}, team interface{}) *TeamRepository_Create_Call {
	return &TeamRepository_Create_Call{Call: _e.mock.On("Create", ctx, team)}
}

func (_c *TeamRepository_Create_Call) Run(run func(ctx context.Context, team *models.Team)) *TeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Team
		if args[1] != nil {
			arg1 = args[1].(*models.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamRepository_Create_Call) Return(err error) *TeamRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamRepository_Create_Call) RunAndReturn(run func(ctx context.Context, team *models.Team) error) *TeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TeamRepository
func (_mock *TeamRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TeamRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TeamRepository_Expecter) Delete(ctx interface{}, id interface{}) *TeamRepository_Delete_Call {
	return &TeamRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TeamRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *TeamRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamRepository_Delete_Call) Return(err error) *TeamRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *TeamRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type TeamRepository
func (_mock *TeamRepository) FindByID(ctx context.Context, id string) (*models.Team, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type TeamRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TeamRepository_Expecter) FindByID(ctx interface{}, id interface{}) *TeamRepository_FindByID_Call {
	return &TeamRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *TeamRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *TeamRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamRepository_FindByID_Call) Return(team *models.Team, err error) *TeamRepository_FindByID_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *TeamRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Team, error)) *TeamRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function for the type TeamRepository
func (_mock *TeamRepository) GetMembers(ctx context.Context, teamID string) ([]models.TeamMember, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []models.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.TeamMember, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.TeamMember); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamRepository_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type TeamRepository_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *TeamRepository_Expecter) GetMembers(ctx interface{}, teamID interface{}) *TeamRepository_GetMembers_Call {
	return &TeamRepository_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, teamID)}
}

func (_c *TeamRepository_GetMembers_Call) Run(run func(ctx context.Context, teamID string)) *TeamRepository_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamRepository_GetMembers_Call) Return(teamMembers []models.TeamMember, err error) *TeamRepository_GetMembers_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *TeamRepository_GetMembers_Call) RunAndReturn(run func(ctx context.Context, teamID string) ([]models.TeamMember, error)) *TeamRepository_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTeams provides a mock function for the type TeamRepository
func (_mock *TeamRepository) GetUserTeams(ctx context.Context, userID string) ([]models.Team, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTeams")
	}

	var r0 []models.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.Team, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Team); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamRepository_GetUserTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTeams'
type TeamRepository_GetUserTeams_Call struct {
	*mock.Call
}

// GetUserTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *TeamRepository_Expecter) GetUserTeams(ctx interface{}, userID interface{}) *TeamRepository_GetUserTeams_Call {
	return &TeamRepository_GetUserTeams_Call{Call: _e.mock.On("GetUserTeams", ctx, userID)}
}

func (_c *TeamRepository_GetUserTeams_Call) Run(run func(ctx context.Context, userID string)) *TeamRepository_GetUserTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamRepository_GetUserTeams_Call) Return(teams []models.Team, err error) *TeamRepository_GetUserTeams_Call {
	_c.Call.Return(teams, err)
	return _c
}

func (_c *TeamRepository_GetUserTeams_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]models.Team, error)) *TeamRepository_GetUserTeams_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TeamRepository
func (_mock *TeamRepository) Update(ctx context.Context, team *models.Team) error {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Team) error); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TeamRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - team *models.Team
func (_e *TeamRepository_Expecter) Update(ctx interface{}, team interface{}) *TeamRepository_Update_Call {
	return &TeamRepository_Update_Call{Call: _e.mock.On("Update", ctx, team)}
}

func (_c *TeamRepository_Update_Call) Run(run func(ctx context.Context, team *models.Team)) *TeamRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Team
		if args[1] != nil {
			arg1 = args[1].(*models.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamRepository_Update_Call) Return(err error) *TeamRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamRepository_Update_Call) RunAndReturn(run func(ctx context.Context, team *models.Team) error) *TeamRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
