// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// NewTeamMemberRepository creates a new instance of TeamMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamMemberRepository {
	mock := &TeamMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TeamMemberRepository is an autogenerated mock type for the TeamMemberRepository type
type TeamMemberRepository struct {
	mock.Mock
}

type TeamMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamMemberRepository) EXPECT() *TeamMemberRepository_Expecter {
	return &TeamMemberRepository_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function for the type TeamMemberRepository
func (_mock *TeamMemberRepository) AddUser(ctx context.Context, teamID string, userID string, role string) error {
	ret := _mock.Called(ctx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, teamID, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamMemberRepository_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type TeamMemberRepository_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - userID string
//   - role string
func (_e *TeamMemberRepository_Expecter) AddUser(ctx interface{}, teamID interface{}, userID interface{}, role interface{}) *TeamMemberRepository_AddUser_Call {
	return &TeamMemberRepository_AddUser_Call{Call: _e.mock.On("AddUser", ctx, teamID, userID, role)}
}

func (_c *TeamMemberRepository_AddUser_Call) Run(run func(ctx context.Context, teamID string, userID string, role string)) *TeamMemberRepository_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TeamMemberRepository_AddUser_Call) Return(err error) *TeamMemberRepository_AddUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamMemberRepository_AddUser_Call) RunAndReturn(run func(ctx context.Context, teamID string, userID string, role string) error) *TeamMemberRepository_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TeamMemberRepository
func (_mock *TeamMemberRepository) Get(ctx context.Context, teamID string, userID string) (*models.TeamMember, error) {
	ret := _mock.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.TeamMember, error)); ok {
		return returnFunc(ctx, teamID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.TeamMember); ok {
		r0 = returnFunc(ctx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamMemberRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TeamMemberRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - userID string
func (_e *TeamMemberRepository_Expecter) Get(ctx interface{}, teamID interface{}, userID interface{}) *TeamMemberRepository_Get_Call {
	return &TeamMemberRepository_Get_Call{Call: _e.mock.On("Get", ctx, teamID, userID)}
}

func (_c *TeamMemberRepository_Get_Call) Run(run func(ctx context.Context, teamID string, userID string)) *TeamMemberRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TeamMemberRepository_Get_Call) Return(teamMember *models.TeamMember, err error) *TeamMemberRepository_Get_Call {
	_c.Call.Return(teamMember, err)
	return _c
}

func (_c *TeamMemberRepository_Get_Call) RunAndReturn(run func(ctx context.Context, teamID string, userID string) (*models.TeamMember, error)) *TeamMemberRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// IsMember provides a mock function for the type TeamMemberRepository
func (_mock *TeamMemberRepository) IsMember(ctx context.Context, teamID string, userID string) (bool, error) {
	ret := _mock.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, teamID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, teamID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamMemberRepository_IsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMember'
type TeamMemberRepository_IsMember_Call struct {
	*mock.Call
}

// IsMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - userID string
func (_e *TeamMemberRepository_Expecter) IsMember(ctx interface{}, teamID interface{}, userID interface{}) *TeamMemberRepository_IsMember_Call {
	return &TeamMemberRepository_IsMember_Call{Call: _e.mock.On("IsMember", ctx, teamID, userID)}
}

func (_c *TeamMemberRepository_IsMember_Call) Run(run func(ctx context.Context, teamID string, userID string)) *TeamMemberRepository_IsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TeamMemberRepository_IsMember_Call) Return(b bool, err error) *TeamMemberRepository_IsMember_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *TeamMemberRepository_IsMember_Call) RunAndReturn(run func(ctx context.Context, teamID string, userID string) (bool, error)) *TeamMemberRepository_IsMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUser provides a mock function for the type TeamMemberRepository
func (_mock *TeamMemberRepository) RemoveUser(ctx context.Context, teamID string, userID string) error {
	ret := _mock.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamMemberRepository_RemoveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUser'
type TeamMemberRepository_RemoveUser_Call struct {
	*mock.Call
}

// RemoveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - userID string
func (_e *TeamMemberRepository_Expecter) RemoveUser(ctx interface{}, teamID interface{}, userID interface{}) *TeamMemberRepository_RemoveUser_Call {
	return &TeamMemberRepository_RemoveUser_Call{Call: _e.mock.On("RemoveUser", ctx, teamID, userID)}
}

func (_c *TeamMemberRepository_RemoveUser_Call) Run(run func(ctx context.Context, teamID string, userID string)) *TeamMemberRepository_RemoveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TeamMemberRepository_RemoveUser_Call) Return(err error) *TeamMemberRepository_RemoveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamMemberRepository_RemoveUser_Call) RunAndReturn(run func(ctx context.Context, teamID string, userID string) error) *TeamMemberRepository_RemoveUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type TeamMemberRepository
func (_mock *TeamMemberRepository) UpdateRole(ctx context.Context, teamID string, userID string, role string) error {
	ret := _mock.Called(ctx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, teamID, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamMemberRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type TeamMemberRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - userID string
//   - role string
func (_e *TeamMemberRepository_Expecter) UpdateRole(ctx interface{}, teamID interface{}, userID interface{}, role interface{}) *TeamMemberRepository_UpdateRole_Call {
	return &TeamMemberRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, teamID, userID, role)}
}

func (_c *TeamMemberRepository_UpdateRole_Call) Run(run func(ctx context.Context, teamID string, userID string, role string)) *TeamMemberRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TeamMemberRepository_UpdateRole_Call) Return(err error) *TeamMemberRepository_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamMemberRepository_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, teamID string, userID string, role string) error) *TeamMemberRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
