// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kkz6/launch-go/internal/modules/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserRepository
func (_mock *UserRepository) Create(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *UserRepository_Expecter) Create(ctx interface{}, user interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, user *models.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(err error) *UserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UserRepository
func (_mock *UserRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepository_Expecter) Delete(ctx interface{}, id interface{}) *UserRepository_Delete_Call {
	return &UserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *UserRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *UserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_Delete_Call) Return(err error) *UserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *UserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function for the type UserRepository
func (_mock *UserRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type UserRepository_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) ExistsByEmail(ctx interface{}, email interface{}) *UserRepository_ExistsByEmail_Call {
	return &UserRepository_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *UserRepository_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_ExistsByEmail_Call) Return(b bool, err error) *UserRepository_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserRepository_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *UserRepository_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type UserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *UserRepository_FindByEmail_Call {
	return &UserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *UserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_FindByEmail_Call) Return(user *models.User, err error) *UserRepository_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *UserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByID(ctx context.Context, id string) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *UserRepository_FindByID_Call {
	return &UserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *UserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_FindByID_Call) Return(user *models.User, err error) *UserRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.User, error)) *UserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailAsVerified provides a mock function for the type UserRepository
func (_mock *UserRepository) MarkEmailAsVerified(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailAsVerified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_MarkEmailAsVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailAsVerified'
type UserRepository_MarkEmailAsVerified_Call struct {
	*mock.Call
}

// MarkEmailAsVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRepository_Expecter) MarkEmailAsVerified(ctx interface{}, userID interface{}) *UserRepository_MarkEmailAsVerified_Call {
	return &UserRepository_MarkEmailAsVerified_Call{Call: _e.mock.On("MarkEmailAsVerified", ctx, userID)}
}

func (_c *UserRepository_MarkEmailAsVerified_Call) Run(run func(ctx context.Context, userID string)) *UserRepository_MarkEmailAsVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_MarkEmailAsVerified_Call) Return(err error) *UserRepository_MarkEmailAsVerified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_MarkEmailAsVerified_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserRepository_MarkEmailAsVerified_Call {
	_c.Call.Return(run)
	return _c
}

// SetCurrentTeam provides a mock function for the type UserRepository
func (_mock *UserRepository) SetCurrentTeam(ctx context.Context, userID string, teamID string) error {
	ret := _mock.Called(ctx, userID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrentTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, teamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_SetCurrentTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCurrentTeam'
type UserRepository_SetCurrentTeam_Call struct {
	*mock.Call
}

// SetCurrentTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
func (_e *UserRepository_Expecter) SetCurrentTeam(ctx interface{}, userID interface{}, teamID interface{}) *UserRepository_SetCurrentTeam_Call {
	return &UserRepository_SetCurrentTeam_Call{Call: _e.mock.On("SetCurrentTeam", ctx, userID, teamID)}
}

func (_c *UserRepository_SetCurrentTeam_Call) Run(run func(ctx context.Context, userID string, teamID string)) *UserRepository_SetCurrentTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_SetCurrentTeam_Call) Return(err error) *UserRepository_SetCurrentTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_SetCurrentTeam_Call) RunAndReturn(run func(ctx context.Context, userID string, teamID string) error) *UserRepository_SetCurrentTeam_Call {
	_c.Call.Return(run)
	return _c
}

// SetOnboarded provides a mock function for the type UserRepository
func (_mock *UserRepository) SetOnboarded(ctx context.Context, userID string, onboarded bool) error {
	ret := _mock.Called(ctx, userID, onboarded)

	if len(ret) == 0 {
		panic("no return value specified for SetOnboarded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, userID, onboarded)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_SetOnboarded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnboarded'
type UserRepository_SetOnboarded_Call struct {
	*mock.Call
}

// SetOnboarded is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - onboarded bool
func (_e *UserRepository_Expecter) SetOnboarded(ctx interface{}, userID interface{}, onboarded interface{}) *UserRepository_SetOnboarded_Call {
	return &UserRepository_SetOnboarded_Call{Call: _e.mock.On("SetOnboarded", ctx, userID, onboarded)}
}

func (_c *UserRepository_SetOnboarded_Call) Run(run func(ctx context.Context, userID string, onboarded bool)) *UserRepository_SetOnboarded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_SetOnboarded_Call) Return(err error) *UserRepository_SetOnboarded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_SetOnboarded_Call) RunAndReturn(run func(ctx context.Context, userID string, onboarded bool) error) *UserRepository_SetOnboarded_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UserRepository
func (_mock *UserRepository) Update(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *UserRepository_Expecter) Update(ctx interface{}, user interface{}) *UserRepository_Update_Call {
	return &UserRepository_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *UserRepository_Update_Call) Run(run func(ctx context.Context, user *models.User)) *UserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_Update_Call) Return(err error) *UserRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Update_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *UserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
