// This file is the canonical example of the testify-suite + mockery pattern
// for the launch-go project. New tests in other modules should follow this
// shape — see internal/modules/auth/services/email_verification_service_test.go.
//
// Why this shape?
//
//   - testify/suite gives a fresh mock per test method via SetupTest, so
//     state cannot leak between cases.
//   - Mocks are autogenerated by mockery (`make mock`) from the contract
//     interfaces, so adding a method to a repository surfaces immediately
//     as a compile error in tests rather than a runtime "method not found"
//     surprise.
//   - The .EXPECT() builder API (mockery v3 default) is type-safe — IDEs
//     autocomplete the argument list and catch signature drift at compile
//     time rather than via a panic at runtime.
//
// Compare with team_member_service_test.go: that file uses hand-rolled mocks
// embedding the interface, which is fine but verbose (~200 lines of mock
// scaffolding). New tests should use this pattern; old tests can migrate
// when they need touching for unrelated reasons.

package services

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/suite"

	"github.com/kkz6/launch-go/internal/config"
	"github.com/kkz6/launch-go/internal/modules/auth/contracts/mocks"
	"github.com/kkz6/launch-go/internal/modules/auth/models"
	basemodels "github.com/kkz6/launch-go/internal/pkg/models"
)

// EmailVerificationServiceSuite wires up a fresh service + mocks for each
// test method.
type EmailVerificationServiceSuite struct {
	suite.Suite

	registry *mocks.RepositoryRegistry
	userRepo *mocks.UserRepository
	cfg      *config.Config
	svc      *EmailVerificationService
}

// SetupTest runs before each Test* method on this suite. Construct mocks
// here so each test starts from a known, empty state.
func (s *EmailVerificationServiceSuite) SetupTest() {
	s.registry = mocks.NewRepositoryRegistry(s.T())
	s.userRepo = mocks.NewUserRepository(s.T())
	s.registry.EXPECT().User().Return(s.userRepo).Maybe()

	s.cfg = &config.Config{
		App: config.AppConfig{Key: "test-app-key-not-real"},
	}

	s.svc = NewEmailVerificationService(s.registry, s.cfg)
}

func TestEmailVerificationServiceSuite(t *testing.T) {
	suite.Run(t, new(EmailVerificationServiceSuite))
}

// makeUser is a tiny helper to keep tests readable. Returns an unverified
// user with the given email.
func makeUser(id, email string) *models.User {
	return &models.User{
		BaseModel: basemodels.BaseModel{ID: id},
		Email:     email,
	}
}

// -------------------------------------------------------------------------
// VerifyEmail
// -------------------------------------------------------------------------

func (s *EmailVerificationServiceSuite) TestVerifyEmail_Success() {
	user := makeUser("user_001", "alice@example.com")
	hash := s.svc.generateEmailHash(user.Email)

	s.userRepo.EXPECT().FindByID(mock.Anything, "user_001").Return(user, nil).Once()
	s.userRepo.EXPECT().MarkEmailAsVerified(mock.Anything, "user_001").Return(nil).Once()

	err := s.svc.VerifyEmail(context.Background(), "user_001", hash)
	s.Require().NoError(err)
}

func (s *EmailVerificationServiceSuite) TestVerifyEmail_AlreadyVerifiedIsNoop() {
	verifiedAt := time.Now().Add(-24 * time.Hour)
	user := makeUser("user_001", "alice@example.com")
	user.EmailVerifiedAt = &verifiedAt
	hash := s.svc.generateEmailHash(user.Email)

	s.userRepo.EXPECT().FindByID(mock.Anything, "user_001").Return(user, nil).Once()
	// MarkEmailAsVerified should NOT be called — assertion enforced by the
	// strict mock cleanup registered in NewUserRepository(t).

	err := s.svc.VerifyEmail(context.Background(), "user_001", hash)
	s.Require().NoError(err)
}

func (s *EmailVerificationServiceSuite) TestVerifyEmail_HashMismatchRejected() {
	user := makeUser("user_001", "alice@example.com")

	s.userRepo.EXPECT().FindByID(mock.Anything, "user_001").Return(user, nil).Once()

	err := s.svc.VerifyEmail(context.Background(), "user_001", "definitely-not-the-real-hash")
	s.Require().Error(err)
	s.Contains(err.Error(), "invalid verification link")
}

func (s *EmailVerificationServiceSuite) TestVerifyEmail_UnknownUserReturnsNotFound() {
	s.userRepo.EXPECT().FindByID(mock.Anything, "user_404").Return(nil, nil).Once()

	err := s.svc.VerifyEmail(context.Background(), "user_404", "anything")
	s.Require().Error(err)
}

// -------------------------------------------------------------------------
// ResendVerificationEmail
// -------------------------------------------------------------------------

func (s *EmailVerificationServiceSuite) TestResendVerificationEmail_RejectsAlreadyVerified() {
	verifiedAt := time.Now()
	user := makeUser("user_001", "alice@example.com")
	user.EmailVerifiedAt = &verifiedAt

	s.userRepo.EXPECT().FindByID(mock.Anything, "user_001").Return(user, nil).Once()

	err := s.svc.ResendVerificationEmail(context.Background(), "user_001")
	s.Require().Error(err)
	s.Contains(err.Error(), "already verified")
}

func (s *EmailVerificationServiceSuite) TestResendVerificationEmail_AllowsUnverified() {
	user := makeUser("user_001", "alice@example.com")

	s.userRepo.EXPECT().FindByID(mock.Anything, "user_001").Return(user, nil).Once()

	// Self-hosted installations without an email sender keep the operation
	// successful while leaving delivery disabled by configuration.
	err := s.svc.ResendVerificationEmail(context.Background(), "user_001")
	s.Require().NoError(err)
}
